# Generated by Django 4.2.4 on 2023-08-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO profiles_profile(
                    user_id,
                    favorite_city
                )
                SELECT
                    user_id,
                    favorite_city
                FROM
                    oc_lettings_site_profile;
                """,
            reverse_sql="""
                INSERT INTO oc_lettings_site_profile(
                    user_id,
                    favorite_city
                    )
                SELECT
                    user_id,
                    favorite_city
                FROM
                    profiles_profile;
                """
        ),
    ]
