# run-name pourrait se servir de Deploy to ${{ inputs.deploy_target }}
name: Build and deploy container app to Azure Web App - Orange-County-Lettings
run-name: Test, Build and deploy container to Azure Web App by @${{ github.actor }}
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['master']

jobs:
  call-tests:
    name: Call the workflow Test
    uses: ./.github/workflows/tests.yml
    secrets: inherit
# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
  push_to_registries:
    name: Push Docker image to multiple registries
    needs: call-tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55
      # So now you can use Actions' own caching!

      - name: Log in to Docker Hub
        uses: docker/login-action@553b6f090f15b58451081ce157ff1929a266131d
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@553b6f090f15b58451081ce157ff1929a266131d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@0f8c876bafbf5dbce05c36682ec68e9a0274a48a
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value={{branch}}@{{sha}}

      - name: Build and push Docker images
        uses: docker/build-push-action@9311bf5263ae5b36f3ec67aff768790c6e2344ad
        with:
          context: .
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DSN=${{ secrets.DSN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
#
  deploy:
    runs-on: ubuntu-latest
    needs: push_to_registries
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@0f8c876bafbf5dbce05c36682ec68e9a0274a48a
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ secrets.APP_NAME }}'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_orange }}
          images: 'docker.io/${{ steps.meta.outputs.tags }}'
#      - name: Login via Az module
#        id: azure-login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#      - name: Restart Web App
#        id: azure-cli
#        run: |
#          az webapp restart --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://github.com/docker/metadata-action

