name: Tests with pytest, Flake8, and Coverage

on: workflow_call

jobs:
  job_1:
      name: Tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
            cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with flake8
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 --exit-zero --format=html --htmldir ./reports/flake8 --max-line-length=99 --statistics --tee --output-file ./reports/flake8/flake8stats.txt
        - name: Test with pytest
          env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
          run: |
            pytest --junitxml=reports/junit/junit.xml --html=reports/junit/report.html
        - name: Test with Coverage
          env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
          run: |
            coverage run -m pytest
            coverage report --data-file=reports/coverage/.coverage
            coverage xml --data-file=reports/coverage/.coverage
            coverage html --data-file=reports/coverage/.coverage

        - name: Archive tests results
          uses: actions/upload-artifact@v3
          with:
            name: tests-reports
            path: reports/